### ISSUE TITLE
Bug: Not working on Mac, cause of \r newlines

### ISSUE THREAD

**Issue by Shinigami92** [nonara/ts-patch#3]
```shell
$> yarn ts-patch install
yarn run v1.21.1
$ ... ts-patch install
env: node\r: No such file or directory
```

Went into the file, saved (replaced all `\n\r` with only `\n`)

Recalled -> Profit

**Comment by nonara** [comment]
Are you referring to `module-patch` files?

\r\n is used in log output and construction of `module-patch.js` and `module-patch.d.ts`

I'm not a Mac user, but I assume the \r shouldn't be a problem for std_out, correct?

**Comment by Shinigami92** [comment]
These two files: https://github.com/nonara/ts-patch/tree/master/src/bin
Only need to change from windows style CRLF to LF only

**Comment by nonara** [comment]
Ok. Would you mind doing one last test for me? (I don't have a way to test on Mac!)

The issues should be fixed. I've switched primary EOL to LF for everything, and to be safe, I've made sure that it's standardized in all built files.

Can you try the following:
- Clone the latest repo
- run `yarn build && yarn test`

That should let us know if it works. The tests currently require npm, btw. If you like, you can also try to install fresh from repo and see if patched version works. When you've confirmed, I'll publish a patch.

Thanks!

**Comment by Shinigami92** [comment]
Will do when I'm at work in few hours 
Was late yesterday 😴

**Comment by Shinigami92** [comment]
Good morning 😄 

```shell
 ~/OpenSource/ts-patch   master  yarn build          
yarn run v1.21.1
$ npm run clean && npm run compile && npm run build:patch
npm WARN lifecycle The node binary used for scripts is /var/folders/ym/y13zvdp55p99ycbl2sz33rp80000gn/T/yarn--1576654694561-0.03799427051034199/node but npm is using /Users/christopher/.nvm/versions/node/v13.1.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ts-patch@1.0.4 clean /Users/christopher/OpenSource/ts-patch
> rimraf dist coverage .nyc_output

sh: rimraf: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! ts-patch@1.0.4 clean: `rimraf dist coverage .nyc_output`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ts-patch@1.0.4 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christopher/.npm/_logs/2019-12-18T07_38_15_057Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


 ✘  ~/OpenSource/ts-patch   master  yarn      
yarn install v1.21.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @types/expect@24.3.0: This is a stub types definition. expect provides its own type definitions, so you do not need this installed.
warning rewire > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 18.59s.


 ~/OpenSource/ts-patch   master  yarn build
yarn run v1.21.1
$ npm run clean && npm run compile && npm run build:patch
npm WARN lifecycle The node binary used for scripts is /var/folders/ym/y13zvdp55p99ycbl2sz33rp80000gn/T/yarn--1576654720751-0.4512576451034289/node but npm is using /Users/christopher/.nvm/versions/node/v13.1.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ts-patch@1.0.4 clean /Users/christopher/OpenSource/ts-patch
> rimraf dist coverage .nyc_output

npm WARN lifecycle The node binary used for scripts is /var/folders/ym/y13zvdp55p99ycbl2sz33rp80000gn/T/yarn--1576654720751-0.4512576451034289/node but npm is using /Users/christopher/.nvm/versions/node/v13.1.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ts-patch@1.0.4 compile /Users/christopher/OpenSource/ts-patch
> tsc

npm WARN lifecycle The node binary used for scripts is /var/folders/ym/y13zvdp55p99ycbl2sz33rp80000gn/T/yarn--1576654720751-0.4512576451034289/node but npm is using /Users/christopher/.nvm/versions/node/v13.1.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ts-patch@1.0.4 build:patch /Users/christopher/OpenSource/ts-patch
> rollup -c


src/patch/main.ts → dist/resources/module-patch.js...
created dist/resources/module-patch.js in 1.6s

src/patch/types.ts → dist/resources/module-patch.d.ts...
created dist/resources/module-patch.d.ts in 500ms
$ node scripts/postbuild.js
✨  Done in 5.56s.


 ~/OpenSource/ts-patch   master  yarn test     
yarn run v1.21.1
$ mocha


  Actions (slow, mostly due to npm)
    ✓ Set Options
    Install
      ✓ Original modules backed up (196ms)
      ✓ All modules patched (215ms)
      ✓ Backs up and patches typescript.d.ts
      ✓ Config file is correct
      ✓ check() is accurate (219ms)
      ✓ Installs dependencies
    Uninstall
      ✓ Removes backup directory
      ✓ Restores original modules (206ms)
      ✓ Restores typescript.d.ts
      ✓ check() is accurate (219ms)
      ✓ Removes dependencies
    Patch
      ✓ Patches single file (1118ms)
      ✓ Patches array of files (1437ms)
      ✓ Patches glob (1412ms)
      ✓ Throws with TS version < 2.7 (211ms)
    Persistence
      Enable
        ✓ Copies hooks
        ✓ Hooks have direct path to persist.js
        ✓ Config file shows persist=true
      Hooks
        ✓ Invokes hooks after new package install
        1) Re-patches modules after hook invoked
        2) Skips patching non-modified module
      Disable
        ✓ Removes hooks files
        ✓ Config file shows persist=false
      Auto-remove
        ✓ Removes hooks files if ts-patch is uninstalled

  CLI
    Action commands run
      ✓ Install
      ✓ Uninstall
      ✓ Patch
      ✓ Unpatch
      ✓ Check
      ✓ --persist
      ✓ --no-persist
    Log commands output
      ✓ Version
      ✓ Invalid command
      Help
        ✓ Header appears
        ✓ All commands appear
        ✓ All args appear
    Parses all options
      ✓ Silent, Verbose
      ✓ Global
      ✓ Basedir
      ✓ Color

  Logger
    ✓ Uses colour if color=true
    ✓ Strips colour if color=false
    CLI Mode
      ✓ Log goes to stdout
      ✓ Error goes to stderr

  Patched Typescript
    PluginCreator
      ✓ should be initialized with empty config
      ✓ should throw error if wrong config entry given
      ✓ should initialize default transformer in before group (139ms)
      ✓ should initialize default transformer in after group
      ✓ should initialize advanced transformer in after group
      ✓ should provide custom config
    Typescript
      ✓ Applies transformer from legacy config (270ms)
      ✓ Applies transformer from default config
      ✓ Merges transformers
      ✓ Runs 3rd party transformers (100ms)
      ✓ Skips ts plugin without errors
    TSC
      ✓ tsc transforms code (1661ms)


  55 passing (19s)
  2 failing

  1) Actions (slow, mostly due to npm)
       Persistence
         Hooks
           Re-patches modules after hook invoked:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/actions.test.ts:218:71)
      at processImmediate (internal/timers.js:439:21)

  2) Actions (slow, mostly due to npm)
       Persistence
         Hooks
           Skips patching non-modified module:

      AssertionError: expected 3 to equal 1
      + expected - actual

      -3
      +1
      
      at Context.<anonymous> (test/actions.test.ts:222:45)
      at processImmediate (internal/timers.js:439:21)



error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nonara** [comment]
@Shinigami92 Thanks! Interesting on the persist thing. It uses npm postinstall hooks. I'll have to look into that if I can get a mac vm going.

Anyway, thanks for the help! Looks like we're good to publish.

**Comment by Shinigami92** [comment]
After more then 24h, npm still dont show up a release 1.0.5? Is it stuck?

**Comment by nonara** [comment]
Whoops. Looks like my global npm registry got overwritten to my company registry! Thanks for letting me know! 🙂
